# Generated by Django 4.2.6 on 2023-11-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="FitnessTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.CharField(max_length=150)),
                ("weight", models.IntegerField(null=True)),
                ("fat", models.IntegerField(null=True)),
                ("progress", models.CharField(max_length=1000)),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                ("diet", models.CharField(max_length=1000)),
                ("water", models.CharField(max_length=1000)),
                ("image", models.ImageField(null=True, upload_to="")),
            ],
        ),
    ]
