# Generated by Django 4.2.6 on 2023-11-04 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0003_fitnesstrack"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fitnesstrack",
            name="date_posted",
        ),
        migrations.RemoveField(
            model_name="thought",
            name="date_posted",
        ),
        migrations.AddField(
            model_name="fitnesstrack",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="thought",
            name="date_now",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
