# Generated by Django 4.2.6 on 2023-11-04 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("journal", "0004_remove_fitnesstrack_date_posted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnesstrack",
            name="user",
            field=models.ForeignKey(
                max_length=10,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
