# Generated by Django 4.2.6 on 2024-04-18 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("journal", "0005_fitnesstrack_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="BMIcal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.IntegerField(null=True)),
                ("height", models.IntegerField(null=True)),
                ("image", models.ImageField(null=True, upload_to="")),
                (
                    "user",
                    models.ForeignKey(
                        max_length=10,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
